version: '3.8'
services:
  back:
    build: ./back
    ports:
      - "4000:4000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  front:
    build: ./front
    ports:
      - "8080:8080"
    depends_on:
      back:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
